# Azure DevOps Pipeline to perform a terraform init & terraform plan
# Matt White @ Microsoft https://github.com/matt-FFFFFF

trigger:
- master

pr:
- master

variables:
  keyvault: tfsecrets-mawhi
  azureservice: azurerm-prod
  TF_IN_AUTOMATION: 1

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureKeyVault@1
  displayName: Get secrets from KeyVault
  inputs:
    ConnectedServiceName: $(azureservice)
    keyVaultName: $(keyvault)
    SecretsFilter: '*'

- script: mkdir $(Agent.WorkFolder)/tf
  displayName: "Create 'tf' directory"

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    TargetFolder: $(Agent.WorkFolder)/tf
    Contents: |
     **/*
     !.git/**/*
  displayName: Copy files to staging directory (excluding .git)

- script: |
    terraform init -input=false -backend-config="container_name=$(terraform-backend-container-name)" \
    -backend-config="access_key=$(terraform-backend-access-key)" \
    -backend-config="key=$(terraform-backend-key)" \
    -backend-config="storage_account_name=$(terraform-backend-storage-account-name)" \
    -backend-config="environment=$(terraform-backend-environment)"
  displayName: Terraform init
  workingDirectory: $(Agent.WorkFolder)/tf

- script: terraform plan -input=false -out='tfplan'
  displayName: Terraform plan
  workingDirectory: $(Agent.WorkFolder)/tf
  env:
    ARM_CLIENT_ID: '$(azurerm-client-id)'
    ARM_CLIENT_SECRET: '$(azurerm-client-secret)'
    ARM_SUBSCRIPTION_ID: '$(azurerm-subscription-id)'
    ARM_TENANT_ID: '$(azurerm-tenant-id)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Agent.WorkFolder)/tf
    ArtifactName: tfplan
  displayName: Copy build artifacts