# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

variables:
  keyvault: tfsecrets-mawhi
  TF_IN_AUTOMATION: 1

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureKeyVault@1
  displayName: Get secrets from KeyVault
  inputs:
    ConnectedServiceName: azurerm-prod
    keyVaultName: $(keyvault)
    SecretsFilter: '*'

- script: cat backend.tfvars
  displayName: List backend secrets

- script: |
    terraform init -input=false -backend-config="container_name=$(terraform-backend-container-name)" \
    -backend-config="access_key=$(terraform-backend-access-key)" \
    -backend-config="key=$(terraform-backend-key)" \
    -backend-config="storage_account_name=$(terraform-backend-storage-account-name)" \
    -backend-config="environment=$(terraform-backend-environment)"
  displayName: Terraform init