# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

variables:
  keyvault: tfsecrets-mawhi

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureKeyVault@1
  displayName: Get secrets from KeyVault
  inputs:
    ConnectedServiceName: azurerm-prod
    keyVaultName: $(keyvault)
    SecretsFilter: '*'

- script: export TF_IN_AUTOMATION=1
  displayName: Set TF automation environment variable

- script: |
    echo "access_key = $terraformbackendaccesskey" > backend.tfvars
    echo "container_name = $terraformbackendcontainername" >>backend.tfvars
    echo "key = $terraformbackendkey" >> backend.tfvars
    echo "storage_account_name = $terraformbackendstorageaccountname" >> backend.tfvars
    echo "environment = $terraformbackendenvironment" >> backend.tfvars
  displayName: 'Write backend secrets file'
  env:
    terraformbackendstorageaccountname: $(terraform-backend-storage-account-name)
    terraformbackendenvironment: $(terraform-backend-environment)
    terraformbackendkey: $(terraform-backend-key)
    terraformbackendcontainername: $(terraform-backend-container-name)
    terraformbackendaccesskey: $(terraform-backend-access-key)

- script: cat backend.tfvars
  displayName: List backend secrets

- script: terraform init -input=false -backend-config="backend.tfvars"
  displayName: Terraform init