# Pipeline to perform a terraform init & terraform plan
# https://aka.ms/yaml

trigger:
- master

pr:
- master

variables:
  keyvault: tfsecrets-mawhi
  azureservice: azurerm-prod
  TF_IN_AUTOMATION: 1

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureKeyVault@1
  displayName: Get secrets from KeyVault
  inputs:
    ConnectedServiceName: $(azureservice)
    keyVaultName: $(keyvault)
    SecretsFilter: '*'

- script: md $(Agent.WorkFolder)/tf
  displayName: Create consistent tf directory

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    TargetFolder: $(Agent.WorkFolder)/tf
    Contents: |
     **/*
     !.git/**/*
  displayName: Copy files to staging directory (excluding .git)

- script: |
    terraform init -input=false -backend-config="container_name=$(terraform-backend-container-name)" \
    -backend-config="access_key=$(terraform-backend-access-key)" \
    -backend-config="key=$(terraform-backend-key)" \
    -backend-config="storage_account_name=$(terraform-backend-storage-account-name)" \
    -backend-config="environment=$(terraform-backend-environment)"
  displayName: Terraform init
  workingDirectory: $(Agent.WorkFolder)/tf

- script: terraform plan -input=false -out='tfplan'
  displayName: Terraform plan
  workingDirectory: $(Agent.WorkFolder)/tf
  env:
    TF_VAR_AZURERM_CLIENT_ID: $(azurerm-client-id)
    TF_VAR_AZURERM_CLIENT_SECRET: $(azurerm-client-secret)
    TF_VAR_AZURERM_SUBSCRIPTION_ID: $(azurerm-subscription-id)
    TF_VAR_AZURERM_TENANT_ID: $(azurerm-tenant-id)

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    TargetFolder: $(Build.ArtifactStagingDirectory)
    Contents: |
     **/*
     !.git/**/*
  displayName: Copy files to staging directory

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Agent.WorkFolder)/tf
    ArtifactName: tfplan
  displayName: Copy build artifacts